use token to access pulrequest API
fixing
Traceback (most recent call last):
  File "scripts/github-fetch-pullrequest", line 80, in <module>
    list_requests()
  File "scripts/github-fetch-pullrequest", line 37, in list_requests
    print request.get('number'), request.get('title')
AttributeError: 'str' object has no attribute 'get'

Caused by exceeding rate limit:
===
https://api.github.com/repos/spacewalkproject/spacewalk/pulls
{
  "message": "API rate limit exceeded for XXX.XXX.XXX.XXX. (But here's the good news: Authent
icated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}